name: "Deploy Server"

on:
  push:
    branches: [master]
    paths: 
      - 'packages/server/**'
  
jobs:
  deploy:
    name: Server Deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Yarn Cache
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Build deployment
      run: yarn build:server

    - name: Yarn Prod Install
      run: yarn install --force --frozen-lockfile --prod

    - name: Upload build
      uses: Burnett01/rsync-deployments@4.0
      with:
        path: packages/server/
        remote_host: ${{secrets.DEPLOY_URL}}
        remote_user: ${{secrets.DEPLOY_USER}}
        remote_path: ${{secrets.SERVER_PATH}}
        switches: -avzr --delete --exclude '.git*' --exclude 'tsconfig.json' --exclude '.vscode' --exclude '**/tsconfig.json' --exclude '.prettierrc' --exclude '**/.git*'
        remote_key: ${{secrets.PRIVATE_KEY}}
        
    - name: Upload Prod Packages
      uses: Brunett01/rsync-deployment@4.0
      with:
        path: node_modules/
        remote_host: ${{secrets.DEPLOY_URL}}
        remote_user: ${{secrets.DEPLOY_USER}}
        remote_path: ${{secrets.SERVER_PATH}}node_modules/
        switches: -avzr --delete
        remote_key: ${{secrets.PRIVATE_KEY}}

    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:
        command: bash ~/server.sh
        host: ${{secrets.DEPLOY_URL}}
        username: ${{secrets.DEPLOY_USER}}
        privateKey: ${{secrets.PRIVATE_KEY}}
